### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'commits'

### ISSUE THREAD

**Issue by Breee** [gotec/git2net#20]
Hey there, 
here another issue on ubuntu 20.04 and python 3.8.5

```
$ git clone https://github.com/gotec/git2net.git
```

```
$ git2net mine ./git2net git2net.db
```

```
$ git2net graph coedit git2net.db git2net_coedit.csv
Traceback (most recent call last):
  File "/home/bree/repos/analysis/venv/bin/git2net", line 8, in <module>
    sys.exit(main())
  File "/home/bree/repos/analysis/venv/lib/python3.8/site-packages/git2net/command_line.py", line 107, in main
    if args.commits:
AttributeError: 'Namespace' object has no attribute 'commits'
```

**Comment by gotec** [comment]
Hi Breee,

I will need to look into this over the weekend. In the meantime, I can suggest using the Python package which also makes the exploration of the resulting networks easier.

Best,
Christoph

**Comment by gotec** [comment]
Merged the pull request. Thanks for the contribution!
